// Code generated by gocc; DO NOT EDIT.

package token

import (
	"fmt"
)

type Token struct {
	Type
	Lit []byte
	Pos
}

type Type int

const (
	INVALID Type = iota
	EOF
)

type Pos struct {
	Offset int
	Line   int
	Column int
}

func (p Pos) String() string {
	return fmt.Sprintf("Pos(offset=%d, line=%d, column=%d)", p.Offset, p.Line, p.Column)
}

type TokenMap struct {
	typeMap []string
	idMap   map[string]Type
}

func (m TokenMap) Id(tok Type) string {
	if int(tok) < len(m.typeMap) {
		return m.typeMap[tok]
	}
	return "unknown"
}

func (m TokenMap) Type(tok string) Type {
	if typ, exist := m.idMap[tok]; exist {
		return typ
	}
	return INVALID
}

func (m TokenMap) TokenString(tok *Token) string {
	//TODO: refactor to print pos & token string properly
	return fmt.Sprintf("%s(%d,%s)", m.Id(tok.Type), tok.Type, tok.Lit)
}

func (m TokenMap) StringType(typ Type) string {
	return fmt.Sprintf("%s(%d)", m.Id(typ), typ)
}

var TokMap = TokenMap{
	typeMap: []string{
		"INVALID",
		"$",
		"function_name",
		"(",
		")",
		"()",
		",",
		"operator_charactor",
		"?",
		":",
		"if",
		"then",
		"else",
		"doublequotes_string",
		"singlequote_string",
		"number",
		"argument",
		"true",
		"false",
		"float",
		"nil",
		"null",
	},

	idMap: map[string]Type{
		"INVALID":             0,
		"$":                   1,
		"function_name":       2,
		"(":                   3,
		")":                   4,
		"()":                  5,
		",":                   6,
		"operator_charactor":  7,
		"?":                   8,
		":":                   9,
		"if":                  10,
		"then":                11,
		"else":                12,
		"doublequotes_string": 13,
		"singlequote_string":  14,
		"number":              15,
		"argument":            16,
		"true":                17,
		"false":               18,
		"float":               19,
		"nil":                 20,
		"null":                21,
	},
}
