// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"io/ioutil"
	"unicode/utf8"

	"github.com/TIBCOSoftware/flogo-lib/core/mapper/exprmapper/expression/gocc/token"
)

const (
	NoState    = -1
	NumStates  = 75
	NumSymbols = 83
)

type Lexer struct {
	src    []byte
	pos    int
	line   int
	column int
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:    src,
		pos:    0,
		line:   1,
		column: 1,
	}
	return lexer
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	return NewLexer(src), nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = new(token.Token)
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '"'
1: '"'
2: '''
3: '''
4: '$'
5: '('
6: ')'
7: '('
8: ')'
9: ','
10: '?'
11: ':'
12: 'i'
13: 'f'
14: 't'
15: 'h'
16: 'e'
17: 'n'
18: 'e'
19: 'l'
20: 's'
21: 'e'
22: 't'
23: 'r'
24: 'u'
25: 'e'
26: 'f'
27: 'a'
28: 'l'
29: 's'
30: 'e'
31: 'n'
32: 'i'
33: 'l'
34: 'n'
35: 'u'
36: 'l'
37: 'l'
38: '-'
39: 'e'
40: 'E'
41: '+'
42: '-'
43: '.'
44: '.'
45: '.'
46: '.'
47: '_'
48: '-'
49: '>'
50: '<'
51: '|'
52: '&'
53: '!'
54: '='
55: '+'
56: '-'
57: '*'
58: '/'
59: '['
60: ']'
61: '.'
62: '-'
63: '['
64: ']'
65: '_'
66: ' '
67: '$'
68: '{'
69: '}'
70: '\'
71: ' '
72: '\t'
73: '\n'
74: '\r'
75: '0'-'9'
76: 'a'-'z'
77: 'A'-'Z'
78: '0'-'9'
79: 'a'-'z'
80: 'A'-'Z'
81: '0'-'9'
82: .
*/
