// Code generated by gocc; DO NOT EDIT.

package parser

import "github.com/TIBCOSoftware/flogo-lib/core/mapper/exprmapper/expression/direction"

type (
	//TODO: change type and variable names to be consistent with other tables
	ProdTab      [numProductions]ProdTabEntry
	ProdTabEntry struct {
		String     string
		Id         string
		NTType     int
		Index      int
		NumSymbols int
		ReduceFunc func([]Attrib) (Attrib, error)
	}
	Attrib interface {
	}
)

var productionsTable = ProdTab{
	ProdTabEntry{
		String: `S' : Flogo	<<  >>`,
		Id:         "S'",
		NTType:     0,
		Index:      0,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Flogo : Expr	<<  >>`,
		Id:         "Flogo",
		NTType:     1,
		Index:      1,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Flogo : TernaryExpr	<<  >>`,
		Id:         "Flogo",
		NTType:     1,
		Index:      2,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `Flogo : IfExpr	<<  >>`,
		Id:         "Flogo",
		NTType:     1,
		Index:      3,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `BaseExpr : Func	<<  >>`,
		Id:         "BaseExpr",
=======
		String: `Expr : OrExpr	<<  >>`,
		Id:         "Expr",
>>>>>>> master
		NTType:     2,
		Index:      4,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `BaseExpr : Expr	<<  >>`,
		Id:         "BaseExpr",
		NTType:     2,
		Index:      5,
		NumSymbols: 1,
=======
		String: `OrExpr : OrExpr "||" AndExpr	<< direction.NewExpression(X[0], X[1], X[2]) >>`,
		Id:         "OrExpr",
		NTType:     3,
		Index:      4,
		NumSymbols: 3,
>>>>>>> master
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewExpression(X[0], X[1], X[2])
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `BaseExpr : Param	<<  >>`,
		Id:         "BaseExpr",
		NTType:     2,
		Index:      6,
=======
		String: `OrExpr : AndExpr	<<  >>`,
		Id:         "OrExpr",
		NTType:     3,
		Index:      5,
>>>>>>> master
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `Func : function_name "(" Args ")"	<< direction.NewFunction(X[0], X[2]) >>`,
		Id:         "Func",
		NTType:     3,
		Index:      7,
		NumSymbols: 4,
=======
		String: `AndExpr : AndExpr "&&" ConditionalExpr	<< direction.NewExpression(X[0], X[1], X[2]) >>`,
		Id:         "AndExpr",
		NTType:     4,
		Index:      6,
		NumSymbols: 3,
>>>>>>> master
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewExpression(X[0], X[1], X[2])
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `Func : function_name "()"	<< direction.NewFunction(X[0], "") >>`,
		Id:         "Func",
		NTType:     3,
		Index:      8,
		NumSymbols: 2,
=======
		String: `AndExpr : ConditionalExpr	<<  >>`,
		Id:         "AndExpr",
		NTType:     4,
		Index:      7,
		NumSymbols: 1,
>>>>>>> master
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `Args : ExprParam	<< direction.NewArgument(X[0]) >>`,
		Id:         "Args",
		NTType:     4,
		Index:      9,
		NumSymbols: 1,
=======
		String: `ConditionalExpr : ConditionalExpr RelOp AddExpr	<< direction.NewExpression(X[0], X[1], X[2]) >>`,
		Id:         "ConditionalExpr",
		NTType:     5,
		Index:      8,
		NumSymbols: 3,
>>>>>>> master
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewExpression(X[0], X[1], X[2])
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `Args : Args "," Args	<< direction.NewArguments(X[0], X[2]) >>`,
		Id:         "Args",
		NTType:     4,
		Index:      10,
		NumSymbols: 3,
=======
		String: `ConditionalExpr : AddExpr	<<  >>`,
		Id:         "ConditionalExpr",
		NTType:     5,
		Index:      9,
		NumSymbols: 1,
>>>>>>> master
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `Expr : ExprArg Operator ExprArg	<< direction.NewExpression(X[0], X[1], X[2]) >>`,
		Id:         "Expr",
		NTType:     5,
		Index:      11,
=======
		String: `AddExpr : AddExpr AddOp MulExpr	<< direction.NewExpression(X[0], X[1], X[2]) >>`,
		Id:         "AddExpr",
		NTType:     6,
		Index:      10,
>>>>>>> master
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewExpression(X[0], X[1], X[2])
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `ExprArg : "(" Expr ")"	<< direction.NewExpressionField(X[1]) >>`,
		Id:         "ExprArg",
=======
		String: `AddExpr : MulExpr	<<  >>`,
		Id:         "AddExpr",
>>>>>>> master
		NTType:     6,
		Index:      12,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewExpressionField(X[1])
		},
	},
	ProdTabEntry{
		String: `ExprArg : Expr	<< direction.NewExpressionField(X[0]) >>`,
		Id:         "ExprArg",
		NTType:     6,
		Index:      13,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `ExprArg : ExprParam	<< direction.NewExpressionField(X[0]) >>`,
		Id:         "ExprArg",
		NTType:     6,
		Index:      14,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewExpressionField(X[0])
=======
		String: `MulExpr : MulExpr MulOp ParenthesesExpr	<< direction.NewExpression(X[0], X[1], X[2]) >>`,
		Id:         "MulExpr",
		NTType:     7,
		Index:      12,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewExpression(X[0], X[1], X[2])
>>>>>>> master
		},
	},
	ProdTabEntry{
		String: `MulExpr : ParenthesesExpr	<<  >>`,
		Id:         "MulExpr",
		NTType:     7,
		Index:      15,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `ParenthesesExpr : ExprLiteral	<<  >>`,
		Id:         "ParenthesesExpr",
		NTType:     8,
<<<<<<< HEAD
		Index:      16,
		NumSymbols: 5,
=======
		Index:      14,
		NumSymbols: 1,
>>>>>>> master
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `IfExpr : "if" BaseExpr Block	<< direction.NewIFF(X[1], X[2]) >>`,
		Id:         "IfExpr",
		NTType:     9,
		Index:      17,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewIFF(X[1], X[2])
		},
	},
	ProdTabEntry{
		String: `IfExpr : "if" BaseExpr Block ElseStatement	<< direction.NewIFFElse(X[1], X[2], X[3]) >>`,
		Id:         "IfExpr",
		NTType:     9,
		Index:      18,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewIFFElse(X[1], X[2], X[3])
		},
	},
	ProdTabEntry{
		String: `Block : "{" Statement "}"	<< direction.NewStatement(X[1]) >>`,
		Id:         "Block",
		NTType:     10,
		Index:      19,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewStatement(X[1])
		},
	},
	ProdTabEntry{
		String: `ElseStatement : "else" IfExpr	<< direction.NewStatement(X[1]) >>`,
		Id:         "ElseStatement",
		NTType:     11,
		Index:      20,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewStatement(X[1])
		},
	},
	ProdTabEntry{
		String: `ElseStatement : "else" Block	<< direction.NewStatement(X[1]) >>`,
		Id:         "ElseStatement",
		NTType:     11,
		Index:      21,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewStatement(X[1])
		},
	},
	ProdTabEntry{
		String: `Statement : IfExpr	<<  >>`,
		Id:         "Statement",
		NTType:     12,
		Index:      22,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Statement : BaseExpr	<<  >>`,
		Id:         "Statement",
		NTType:     12,
		Index:      23,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Statement : TernaryExpr	<<  >>`,
		Id:         "Statement",
		NTType:     12,
		Index:      24,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `ExprParam : Param	<< direction.NewExpressionField(X[0]) >>`,
		Id:         "ExprParam",
		NTType:     13,
		Index:      25,
		NumSymbols: 1,
=======
		String: `ParenthesesExpr : "(" Expr ")"	<< direction.NewExpressionField(X[1]) >>`,
		Id:         "ParenthesesExpr",
		NTType:     8,
		Index:      15,
		NumSymbols: 3,
>>>>>>> master
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewExpressionField(X[1])
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `ExprParam : Func	<< direction.NewExpressionField(X[0]) >>`,
		Id:         "ExprParam",
		NTType:     13,
		Index:      26,
=======
		String: `RelOp : "=="	<<  >>`,
		Id:         "RelOp",
		NTType:     9,
		Index:      16,
>>>>>>> master
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `Param : Int	<<  >>`,
		Id:         "Param",
		NTType:     14,
		Index:      27,
=======
		String: `RelOp : "!="	<<  >>`,
		Id:         "RelOp",
		NTType:     9,
		Index:      17,
>>>>>>> master
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `Param : Float	<<  >>`,
		Id:         "Param",
		NTType:     14,
		Index:      28,
=======
		String: `RelOp : "<"	<<  >>`,
		Id:         "RelOp",
		NTType:     9,
		Index:      18,
>>>>>>> master
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `Param : Bool	<<  >>`,
		Id:         "Param",
		NTType:     14,
		Index:      29,
=======
		String: `RelOp : "<="	<<  >>`,
		Id:         "RelOp",
		NTType:     9,
		Index:      19,
>>>>>>> master
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `Param : DoubleQString	<<  >>`,
		Id:         "Param",
		NTType:     14,
		Index:      30,
=======
		String: `RelOp : ">"	<<  >>`,
		Id:         "RelOp",
		NTType:     9,
		Index:      20,
>>>>>>> master
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `Param : SingleQString	<<  >>`,
		Id:         "Param",
		NTType:     14,
		Index:      31,
=======
		String: `RelOp : ">="	<<  >>`,
		Id:         "RelOp",
		NTType:     9,
		Index:      21,
>>>>>>> master
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `Param : MappingRef	<<  >>`,
		Id:         "Param",
		NTType:     14,
		Index:      32,
=======
		String: `AddOp : "+"	<<  >>`,
		Id:         "AddOp",
		NTType:     10,
		Index:      22,
>>>>>>> master
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `Param : Nil	<<  >>`,
		Id:         "Param",
		NTType:     14,
		Index:      33,
=======
		String: `AddOp : "-"	<<  >>`,
		Id:         "AddOp",
		NTType:     10,
		Index:      23,
>>>>>>> master
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `DoubleQString : doublequotes_string	<< direction.NewDoubleQuoteStringLit(X[0]) >>`,
		Id:         "DoubleQString",
		NTType:     15,
		Index:      34,
=======
		String: `MulOp : "*"	<<  >>`,
		Id:         "MulOp",
		NTType:     11,
		Index:      24,
>>>>>>> master
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `SingleQString : singlequote_string	<< direction.NewSingleQuoteStringLit(X[0]) >>`,
		Id:         "SingleQString",
		NTType:     16,
		Index:      35,
=======
		String: `MulOp : "/"	<<  >>`,
		Id:         "MulOp",
		NTType:     11,
		Index:      25,
>>>>>>> master
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `Int : number	<< direction.NewIntLit(X[0]) >>`,
		Id:         "Int",
		NTType:     17,
		Index:      36,
=======
		String: `MulOp : "%!"(MISSING)	<<  >>`,
		Id:         "MulOp",
		NTType:     11,
		Index:      26,
>>>>>>> master
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `MappingRef : argument	<< direction.NewMappingRef(X[0]) >>`,
		Id:         "MappingRef",
		NTType:     18,
		Index:      37,
=======
		String: `Func : function_name "(" ArgsList ")"	<< direction.NewFunction(X[0], X[2]) >>`,
		Id:         "Func",
		NTType:     12,
		Index:      27,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewFunction(X[0], X[2])
		},
	},
	ProdTabEntry{
		String: `Func : function_name "()"	<< direction.NewFunction(X[0], "") >>`,
		Id:         "Func",
		NTType:     12,
		Index:      28,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewFunction(X[0], "")
		},
	},
	ProdTabEntry{
		String: `ArgsList : ExprLiteral	<< direction.NewArgument(X[0]) >>`,
		Id:         "ArgsList",
		NTType:     13,
		Index:      29,
>>>>>>> master
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewArgument(X[0])
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `Bool : "true"	<< direction.NewBool(X[0]) >>`,
		Id:         "Bool",
		NTType:     19,
		Index:      38,
=======
		String: `ArgsList : ArgsList "," ArgsList	<< direction.NewArguments(X[0], X[2]) >>`,
		Id:         "ArgsList",
		NTType:     13,
		Index:      30,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewArguments(X[0], X[2])
		},
	},
	ProdTabEntry{
		String: `TernaryExpr : Expr "?" Expr ":" Expr	<< direction.NewTernaryExpression(X[0], X[2], X[4]) >>`,
		Id:         "TernaryExpr",
		NTType:     14,
		Index:      31,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewTernaryExpression(X[0], X[2], X[4])
		},
	},
	ProdTabEntry{
		String: `ExprLiteral : Literal	<< direction.NewLiteralExpr(X[0]) >>`,
		Id:         "ExprLiteral",
		NTType:     15,
		Index:      32,
>>>>>>> master
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewLiteralExpr(X[0])
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `Bool : "false"	<< direction.NewBool(X[0]) >>`,
		Id:         "Bool",
		NTType:     19,
		Index:      39,
=======
		String: `ExprLiteral : Func	<<  >>`,
		Id:         "ExprLiteral",
		NTType:     15,
		Index:      33,
>>>>>>> master
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `Float : float	<< direction.NewFloatLit(X[0]) >>`,
		Id:         "Float",
		NTType:     20,
		Index:      40,
=======
		String: `Literal : Int	<< direction.NewIntLit(X[0]) >>`,
		Id:         "Literal",
		NTType:     16,
		Index:      34,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewIntLit(X[0])
		},
	},
	ProdTabEntry{
		String: `Literal : Float	<< direction.NewFloatLit(X[0]) >>`,
		Id:         "Literal",
		NTType:     16,
		Index:      35,
>>>>>>> master
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewFloatLit(X[0])
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `Nil : "nil"	<< direction.NewNilLit(X[0]) >>`,
		Id:         "Nil",
		NTType:     21,
		Index:      41,
=======
		String: `Literal : Bool	<< direction.NewBool(X[0]) >>`,
		Id:         "Literal",
		NTType:     16,
		Index:      36,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewBool(X[0])
		},
	},
	ProdTabEntry{
		String: `Literal : DoubleQString	<< direction.NewDoubleQuoteStringLit(X[0]) >>`,
		Id:         "Literal",
		NTType:     16,
		Index:      37,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewDoubleQuoteStringLit(X[0])
		},
	},
	ProdTabEntry{
		String: `Literal : SingleQString	<< direction.NewSingleQuoteStringLit(X[0]) >>`,
		Id:         "Literal",
		NTType:     16,
		Index:      38,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewSingleQuoteStringLit(X[0])
		},
	},
	ProdTabEntry{
		String: `Literal : MappingRef	<< direction.NewMappingRef(X[0]) >>`,
		Id:         "Literal",
		NTType:     16,
		Index:      39,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewMappingRef(X[0])
		},
	},
	ProdTabEntry{
		String: `Literal : Nil	<< direction.NewNilLit(X[0]) >>`,
		Id:         "Literal",
		NTType:     16,
		Index:      40,
>>>>>>> master
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return direction.NewNilLit(X[0])
		},
	},
	ProdTabEntry{
<<<<<<< HEAD
		String: `Nil : "null"	<< direction.NewNilLit(X[0]) >>`,
		Id:         "Nil",
		NTType:     21,
		Index:      42,
=======
		String: `DoubleQString : doublequotes_string	<<  >>`,
		Id:         "DoubleQString",
		NTType:     17,
		Index:      41,
>>>>>>> master
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `SingleQString : singlequote_string	<<  >>`,
		Id:         "SingleQString",
		NTType:     18,
		Index:      42,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Int : number	<<  >>`,
		Id:         "Int",
		NTType:     19,
		Index:      43,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `MappingRef : argument	<<  >>`,
		Id:         "MappingRef",
		NTType:     20,
		Index:      44,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Bool : "true"	<<  >>`,
		Id:         "Bool",
		NTType:     21,
		Index:      45,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Bool : "false"	<<  >>`,
		Id:         "Bool",
		NTType:     21,
		Index:      46,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Float : float	<<  >>`,
		Id:         "Float",
		NTType:     22,
		Index:      47,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Nil : "nil"	<<  >>`,
		Id:         "Nil",
		NTType:     23,
		Index:      48,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Nil : "null"	<<  >>`,
		Id:         "Nil",
		NTType:     23,
		Index:      49,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
}
